# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : rouge
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true
blog-site : true

#source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO Site settings
title: MyPublic
primtitle: My
subtitle: Public
description: "Meu blog pessoal using Jekyll"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: "http://sjodiel.github.io"
# baseurl: ""

google_analytics: UA-27342987-1
repo: http://github.com/sjodiel
disqus_shortname: "sjodiel"
disqus_site_shortname: "sjodiel"
github-corner: false

# Author settings
author:
  Hello     : "Olá!.."
  Iam       : Eu sou
  name      : Jodiel Fabricio
  a         : um futuro
  job       : Cientista da Computação
  bio       : "Adoro um bom café, e espero viver o suficiente para lhe conhecer. ;)"
  thumb     : /images/author.jpg
  email     : jodielfabricio@gmail.com
  url       : http://sjodiel.cashmore.com.br
  github    : http://github.com/sjodiel 
  twitter   : http://twitter.com/sjodiel  
  facebook  : http://facebook.com/sjodiel
  linkedin  : http://linkedin.com/in/sjodiel

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog
